module Navigation
  class Airport < Waypoint
    include NavigationStorage

    attr_reader fullname: String

    attr_reader altitude: Altitude

    attr_reader runways: Array[Runway]

    # Constructor for the Airport object
    # rubocop: disable Metrics/ParameterLists - parameters defined by the import file.  Prefer the type checking.
    def initialize: (name: String name, fullname: String fullname, altitude: (Altitude|Integer) altitude,
                     latitude: (Angle|Numeric) latitude, longitude: (Angle|Numeric) longitude,
                     runways: Array[Runway] runways) -> void
  end
end
