module Flightplan
  # Flightplan describes the flightplan the aircraft is following.  It is made up of a sequence of paths with the
  # first element of the sequence being the current active path being followed.
  class Flightplan
    attr_reader departure_airport: untyped

    def initialize: (departure_airport: untyped departure_airport, enroute: untyped enroute) -> untyped

    def desired_heading: (untyped position) -> untyped

    def current: () -> (Navigation::AirwaySegment)

    def []: (Integer index) -> Flightplan

    def transmit: () -> Flightplan

    def routing: (departure_airport: Navigation::Airport departure_airport, enroute: String enroute) -> untyped

    def fly_direct: (Navigation::Waypoint waypoint) -> Flightplan

    def then_as_filed: () -> Flightplan

    def fly_heading: (Angle heading) -> Flightplan

    def climb_to: (Altitude altitude) -> Flightplan

    def no_speed_restrictions: () -> Flightplan
  end
end
